export const initialCandidates = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "+91 9876543210",
    location: "Delhi",
    experience: "3 years",
    education: "B.Tech Computer Science",
    status: "Verified",
    skills: ["React", "Node.js", "JavaScript", "MongoDB"],
    appliedJobs: 5,
    lastActive: "2024-03-20",
  },
  {
    id: 2,
    name: "Priya Patel",
    email: "priya.patel@example.com",
    phone: "+91 9876543211",
    location: "Mumbai",
    experience: "2 years",
    education: "MCA",
    status: "Verified",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    appliedJobs: 3,
    lastActive: "2024-03-19",
  },
  {
    id: 3,
    name: "Amit Kumar",
    email: "amit.kumar@example.com",
    phone: "+91 9876543212",
    location: "Bangalore",
    experience: "5 years",
    education: "M.Tech Software Engineering",
    status: "Not Verified",
    skills: ["Java", "Spring Boot", "AWS", "Microservices"],
    appliedJobs: 8,
    lastActive: "2024-03-18",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    phone: "+91 9876543213",
    location: "Hyderabad",
    experience: "1 year",
    education: "B.Sc Computer Science",
    status: "Verified",
    skills: ["JavaScript", "React", "CSS", "HTML"],
    appliedJobs: 2,
    lastActive: "2024-03-17",
  },
  {
    id: 5,
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    phone: "+91 9876543214",
    location: "Chennai",
    experience: "4 years",
    education: "B.E Computer Engineering",
    status: "Verified",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL"],
    appliedJobs: 6,
    lastActive: "2024-03-16",
  },
  {
    id: 6,
    name: "Anjali Mehta",
    email: "anjali.mehta@example.com",
    phone: "+91 9876543215",
    location: "Pune",
    experience: "6 years",
    education: "MBA IT",
    status: "Not Verified",
    skills: ["Product Management", "Agile", "JIRA", "Analytics"],
    appliedJobs: 4,
    lastActive: "2024-03-15",
  },
  {
    id: 7,
    name: "Rajesh Gupta",
    email: "rajesh.gupta@example.com",
    phone: "+91 9876543216",
    location: "Ahmedabad",
    experience: "2.5 years",
    education: "B.Tech IT",
    status: "Verified",
    skills: ["PHP", "Laravel", "MySQL", "JavaScript"],
    appliedJobs: 3,
    lastActive: "2024-03-14",
  },
  {
    id: 8,
    name: "Neha Verma",
    email: "neha.verma@example.com",
    phone: "+91 9876543217",
    location: "Kolkata",
    experience: "3.5 years",
    education: "M.Sc Computer Science",
    status: "Verified",
    skills: ["Angular", "TypeScript", "Node.js", "MongoDB"],
    appliedJobs: 7,
    lastActive: "2024-03-13",
  },
  {
    id: 9,
    name: "David Wilson",
    email: "david.wilson@example.com",
    phone: "+1 2345678901",
    location: "London",
    experience: "8 years",
    education: "MS Computer Science",
    status: "Not Verified",
    skills: ["Go", "Docker", "Kubernetes", "AWS"],
    appliedJobs: 10,
    lastActive: "2024-03-12",
  },
  {
    id: 10,
    name: "Sara Johnson",
    email: "sara.johnson@example.com",
    phone: "+1 2345678902",
    location: "New York",
    experience: "7 years",
    education: "PhD Artificial Intelligence",
    status: "Verified",
    skills: ["AI", "Deep Learning", "Python", "PyTorch"],
    appliedJobs: 5,
    lastActive: "2024-03-11",
  },
];
