export const initialJobs = [
  {
    id: 1,
    title: "Senior React Developer",
    company: "TechCorp Solutions",
    location: "Remote",
    salary: "₹15-25 LPA",
    experience: "3-5 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-03-15",
    applicants: 45,
    requirements: "React, TypeScript, Node.js",
    description:
      "Looking for experienced React developer with 3+ years experience...",
  },
  {
    id: 2,
    title: "Frontend Engineer",
    company: "MedLife Healthcare",
    location: "Delhi",
    salary: "₹12-18 LPA",
    experience: "2-4 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-03-10",
    applicants: 32,
    requirements: "JavaScript, React, CSS",
    description: "Frontend developer for healthcare application...",
  },
  {
    id: 3,
    title: "Backend Developer",
    company: "EduTech Innovations",
    location: "Bangalore",
    salary: "₹18-30 LPA",
    experience: "4-6 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-03-05",
    applicants: 28,
    requirements: "Node.js, MongoDB, AWS",
    description: "Senior backend developer for EdTech platform...",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    company: "AutoMakers Ltd",
    location: "Chennai",
    salary: "₹10-15 LPA",
    experience: "2-3 years",
    type: "Full-time",
    status: "paused",
    postedDate: "2024-02-28",
    applicants: 18,
    requirements: "Figma, Adobe XD, User Research",
    description: "UI/UX designer for automotive platform...",
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "FinSecure Capital",
    location: "Mumbai",
    salary: "₹20-35 LPA",
    experience: "5-7 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-02-20",
    applicants: 22,
    requirements: "Docker, Kubernetes, AWS, CI/CD",
    description: "DevOps engineer for financial services...",
  },
  {
    id: 6,
    title: "Data Scientist",
    company: "Global Logistics Inc",
    location: "Remote",
    salary: "₹25-40 LPA",
    experience: "4-6 years",
    type: "Contract",
    status: "active",
    postedDate: "2024-02-15",
    applicants: 15,
    requirements: "Python, ML, SQL, Statistics",
    description: "Data scientist for logistics optimization...",
  },
  {
    id: 7,
    title: "Mobile Developer",
    company: "AgroFarm Solutions",
    location: "Hyderabad",
    salary: "₹8-12 LPA",
    experience: "1-3 years",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-02-10",
    applicants: 40,
    requirements: "React Native, JavaScript",
    description: "Mobile app developer for agriculture platform...",
  },
  {
    id: 8,
    title: "Product Manager",
    company: "RealEstate Developers",
    location: "Delhi",
    salary: "₹25-40 LPA",
    experience: "5-8 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-02-05",
    applicants: 25,
    requirements: "Product Strategy, Agile, Analytics",
    description: "Product manager for real estate platform...",
  },
  {
    id: 9,
    title: "QA Engineer",
    company: "Retail Chain India",
    location: "Bangalore",
    salary: "₹6-10 LPA",
    experience: "1-2 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-01-30",
    applicants: 35,
    requirements: "Manual Testing, Automation, Selenium",
    description: "Quality assurance engineer for retail platform...",
  },
  {
    id: 10,
    title: "Sales Executive",
    company: "UK Tech Solutions",
    location: "London",
    salary: "£30-40k",
    experience: "2-3 years",
    type: "Full-time",
    status: "active",
    postedDate: "2024-01-25",
    applicants: 20,
    requirements: "Sales, Communication, CRM",
    description: "Sales executive for UK market...",
  },
];
