export const initialCompanies = [
  {
    id: 1,
    name: "TechCorp Solutions",
    email: "contact@techcorp.com",
    phone: "+91 9876543210",
    registrationDate: "2024-01-15",
    country: "India",
    status: "verified",
    industry: "IT Services",
    jobsPosted: 24,
    walletBalance: 125000,
  },
  {
    id: 2,
    name: "MedLife Healthcare",
    email: "info@medlife.com",
    phone: "+91 9876543211",
    registrationDate: "2024-02-10",
    country: "India",
    status: "verified",
    industry: "Healthcare",
    jobsPosted: 18,
    walletBalance: 85000,
  },
  {
    id: 3,
    name: "EduTech Innovations",
    email: "support@edutech.com",
    phone: "+91 9876543212",
    registrationDate: "2024-03-05",
    country: "India",
    status: "pending",
    industry: "Education",
    jobsPosted: 0,
    walletBalance: 0,
  },
  {
    id: 4,
    name: "AutoMakers Ltd",
    email: "contact@automakers.com",
    phone: "+91 9876543213",
    registrationDate: "2024-01-25",
    country: "India",
    status: "verified",
    industry: "Manufacturing",
    jobsPosted: 32,
    walletBalance: 210000,
  },
  {
    id: 5,
    name: "FinSecure Capital",
    email: "info@finsecure.com",
    phone: "+91 9876543214",
    registrationDate: "2024-04-01",
    country: "India",
    status: "pending",
    industry: "Finance",
    jobsPosted: 0,
    walletBalance: 0,
  },
  {
    id: 6,
    name: "Global Logistics Inc",
    email: "contact@globallogistics.com",
    phone: "+1 2345678901",
    registrationDate: "2024-02-20",
    country: "USA",
    status: "verified",
    industry: "Logistics",
    jobsPosted: 15,
    walletBalance: 75000,
  },
  {
    id: 7,
    name: "AgroFarm Solutions",
    email: "info@agrofarm.com",
    phone: "+91 9876543215",
    registrationDate: "2024-03-15",
    country: "India",
    status: "pending",
    industry: "Agriculture",
    jobsPosted: 0,
    walletBalance: 0,
  },
  {
    id: 8,
    name: "RealEstate Developers",
    email: "contact@realestate.com",
    phone: "+91 9876543216",
    registrationDate: "2024-01-10",
    country: "India",
    status: "verified",
    industry: "Real Estate",
    jobsPosted: 28,
    walletBalance: 180000,
  },
  {
    id: 9,
    name: "Retail Chain India",
    email: "support@retailchain.com",
    phone: "+91 9876543217",
    registrationDate: "2024-03-25",
    country: "India",
    status: "pending",
    industry: "Retail",
    jobsPosted: 0,
    walletBalance: 0,
  },
  {
    id: 10,
    name: "UK Tech Solutions",
    email: "info@uktech.com",
    phone: "+44 1234567890",
    registrationDate: "2024-02-05",
    country: "UK",
    status: "verified",
    industry: "IT Services",
    jobsPosted: 20,
    walletBalance: 95000,
  },
];
